package com.example.ecommercespring.Entity;
//instant class from java time API> represent the timestamp in UTC
import java.time.Instant;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;
//import jpa annotations  like @Id, @column, used to mapping clas  to a db structure
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;


//is JPA annotation use dto define the base class gthat contains the common fields
//which will be inherited and mapped into child entity tables
//unlike @entity > it does not get its own table-> just to remove repeated fields
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter

public class BaseEntity {
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY /*autogenerated and increment the value*/)
public long id;

@CreatedDate
@Column(nullable = false,updatable = false)
private Instant createdAt;

@LastModifiedDate
@Column(nullable = false)
private Instant updatedAt;


//how to populate the value -below methods

@PrePersist //this method is automatically called before the entity is saved for the first time
public void onCreate(){
    Instant now=Instant.now();
    this.createdAt=now;
    this.updatedAt=now;
}

@PreUpdate
public void onUpdate(){
    this.updatedAt=Instant.now();
}

}
